import Todo_Container from '@/containers/Todo_Container'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='font-roboto h-screen w-screen bg-bg_color grid place-items-center'>
        <Todo_Container />
      </main>
    </>
  )
}
